const {chromium}=require(process.env.OPEN_FIELD_PLAYWRIGHT || 'playwright');
const fs=require('fs');const path=require('path');const assert=require('assert');
const OUT=path.resolve(process.argv[2] || path.join(__dirname,'../submission')), ROOT=path.join(OUT,'qa'); fs.mkdirSync(ROOT,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.OPEN_FIELD_BROWSER?{executablePath:process.env.OPEN_FIELD_BROWSER}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1080},deviceScaleFactor:1,acceptDownloads:true});
 const page=await context.newPage(), errors=[], requests=[];
 page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push(r.url()));
 const file='file:///'+path.join(OUT,'Open-Field.html').replaceAll('\\','/');
 await page.goto(file);await page.waitForFunction(()=>!!window.OpenFieldApp && document.querySelector('#scrubber').value==='2.3');
 assert.equal(await page.locator('#receiver-a').inputValue(),'43454');
 assert.equal(await page.locator('#scrubber').inputValue(),'2.3');
 await page.screenshot({path:path.join(OUT,'Open-Field-preview.png'),fullPage:true});
 await page.locator('#storyCompare').click();
 assert.equal(await page.locator('#receiver-b').inputValue(),'47839');
 assert.equal(await page.locator('.board').count(),2);
 await page.locator('#scrubber').fill('6.2');
 assert(await page.locator('.ended-flag').first().isVisible());
 await page.screenshot({path:path.join(ROOT,'compare-ui.png'),fullPage:true});
 const endedDownloadPromise=page.waitForEvent('download');await page.locator('#exportButton').click();
 await (await endedDownloadPromise).saveAs(path.join(ROOT,'ended-export.png'));
 const timeline=await page.evaluate(()=>[...document.querySelectorAll('.timeline')].map(c=>({aria:c.getAttribute('aria-label'),width:c.width,height:c.height})));
 await page.locator('[data-mode="change"]').click();
 await page.locator('#resetButton').click();
 assert.equal(await page.locator('.history-note:visible').count(),2);
 const historyDownloadPromise=page.waitForEvent('download');await page.locator('#exportButton').click();
 await (await historyDownloadPromise).saveAs(path.join(ROOT,'history-export.png'));
 await page.locator('#scrubber').fill('2.3');
 assert.equal(await page.locator('.history-note:visible').count(),0);
 const downloadPromise=page.waitForEvent('download');await page.locator('#exportButton').click();
 const download=await downloadPromise;await download.saveAs(path.join(OUT,'Open-Field-comparison.png'));
 const png=fs.readFileSync(path.join(OUT,'Open-Field-comparison.png'));
 assert.equal(png.toString('hex',0,8),'89504e470d0a1a0a');
 await page.locator('#storySelect').selectOption('2');
 await page.locator('#storyCompare').click();
 const same=await page.evaluate(()=>({a:OpenFieldApp.state.a,b:OpenFieldApp.state.b,receivers:OpenFieldApp.state.receivers}));
 assert.equal(same.a,same.b);assert.notEqual(same.receivers.a,same.receivers.b);
 await page.locator('#search').fill('no-match-qzj');
 assert.equal(await page.locator('.play-option').count(),0);
 await page.locator('#search').fill('Tyreek Hill');
 assert((await page.locator('.play-option').count())>0);
 await page.locator('#search').fill('');
 await page.locator('#filterOffense').selectOption('NYG');
 const filtered=await page.evaluate(()=>OpenFieldApp.state.filtered.map(p=>p.offense));
 assert(filtered.length>0&&filtered.every(x=>x==='NYG'));
 await page.locator('#filterOffense').selectOption('');
 await page.locator('#storySelect').selectOption('0');
 if(await page.locator('#removeCompare').isVisible())await page.locator('#removeCompare').click();
 await page.locator('#downfieldOnly').uncheck();
 const all=await page.locator('.total-window').innerText();
 await page.locator('#downfieldOnly').check();
 const downfield=await page.locator('.total-window').innerText();
 assert(parseFloat(downfield)<=parseFloat(all));
 await page.locator('#threshold').fill('5');
 assert.equal(await page.locator('#thresholdValue').innerText(),'5.0 yd');
 await page.locator('#threshold').fill('3');
 await page.locator('#methodButton').click();assert(await page.locator('#methodDialog').isVisible());
 await page.keyboard.press('Escape');assert(!(await page.locator('#methodDialog').isVisible()));
 await page.locator('#resetButton').click();await page.locator('#stepForward').click();
 assert.equal(await page.locator('#scrubber').inputValue(),'0.1');
 await page.locator('#speed').selectOption('2');await page.locator('#playButton').click();
 await page.waitForFunction(()=>OpenFieldApp.state.playing===false&&OpenFieldApp.state.t>4,{},{timeout:8000});
 assert.equal(await page.locator('#scrubber').inputValue(),'4.1');
 await page.locator('[data-mode="distance"]').click();
 await page.setViewportSize({width:390,height:844});
 await page.waitForTimeout(200);
 const mobile=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth}));
 assert(mobile.width<=mobile.viewport,'Mobile horizontal overflow');
 await page.screenshot({path:path.join(ROOT,'mobile-ui.png'),fullPage:true});
 await page.locator('#compareButton').click();
 await page.waitForTimeout(100);
 const compareMobile=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth}));
 assert(compareMobile.width<=compareMobile.viewport,'Mobile comparison overflow');
 await page.screenshot({path:path.join(ROOT,'mobile-compare-ui.png'),fullPage:true});
 assert.equal(errors.length,0,errors.join('\n'));
 const external=requests.filter(u=>/^https?:/.test(u));assert.equal(external.length,0,'Offline demo fetched external resources');
 const report={status:'passed',checks:['offline load','default curated example','comparison and short-play endpoint','half-second history guard','PNG export','same-play different-receiver comparison','empty search','all-player-name search','offense filter','downfield toggle','threshold update','method dialog keyboard dismissal','frame stepping','playback stops at release','390px layout','390px comparison layout','zero JavaScript errors','no external network requests'],errors,externalRequests:external,mobile,compareMobile,timeline,png:{width:png.readUInt32BE(16),height:png.readUInt32BE(20)}};
 fs.writeFileSync(path.join(ROOT,'browser-qa.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
